# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3408da8d1b89716ee9c093beea9c5af70ec1786c01d539b522ae63fa9cb32f1c1e95fdd7d60d93f0e2ab2fd1d278d5d6e8f21b13da2da912739e3e88fad461b

test:
  secret_key_base: c354dcd89ef6b962d3cdadacffacdda216537879a0aeaecf729a05fc44e9f14c2c150ef706613f1c0103d2f7c0c2a06de0b885da57512d8531d5da3a21492f81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
